name: Enable Automerge
on:
  pull_request:
    branches:
      - main
jobs:

  Enable-Automerge:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Auto Merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.github_token}}
